name: dynatype
description: The package helps developers make the process easy by validating the response of type JSON. The person using this package does not need to worry about any exception in JSON Map Entries. He can define a pattern for the JSON response using DynaType.
version: 1.0.3
homepage: https://github.com/chetanxpatil/dynatype

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  equatable: ^2.0.3


dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
