name: dynatype
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/chetanxpatil/dynatype

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  equatable: ^2.0.3


dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
