name: dynatype
description: The package helps developers make the process easy by validating the response of type JSON. The person using this package does not need to worry about any exception in JSON Map Entries.
version: 2.0.0
homepage: https://github.com/chetanxpatil/dynatype

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  equatable: ^2.0.5


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
